# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbfd20f1e852074fb5a60e84e319dd203adcb5d5e789617d8c13803c51309d7dd612dfb455ab7a0467b66b1ddf452e66aef2f54033aeb5cef3334b6fe57b3b47

test:
  secret_key_base: 1487d42b95073b666075c8730ff9f0133a861ba2ca42a8358d2527e747206bc030386028d6282be231ca7c126f15d4fb0a9f2428b9e3401392d6607f8e5fdad7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
